version: '3.8'
services:

  api:
    build: 
      context: ./
      target: workoutly-api
    environment:
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mongo:4.4
    container_name: workoutly-db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./db.js:/docker-entrypoint-initdb.d/db.js:rw
      - ./mongo-volume:/data/db
      - ./.env:/.env
    ports:
      - "27017:27017"
